### ISSUE TITLE
SparkLoggingEvent Filtering rule not working as expected

### ISSUE THREAD

**Issue by hungnguyen10897** [mspnp/spark-monitoring#144] opened 2021-07-19 10:45 UTC
We are currently using this Filter rule for the `SparkLoggingEvent`.
```
export LA_SPARKLOGGINGEVENT_NAME_REGEX=".*\$read\$.*"
```
This essentially picks events with `logger_name` to contain "$read$". It seems that this regex matches everything thus shipping all `SparkLoggingEvent` events.

Observed on Databricks runtime 8.3, haven't tested on other runtimes.

**Comment by hallihan** [comment] 2021-09-10 19:35
It looks like this has to do with how the shell is parsing the `\$` and subsequently how it decides if something like `$read` is a variable that it needs to expand.  Basically the spark-monitoring.sh file is going to cause the escape characters to be processed one time, and then the resulting spark-env.sh is going to process them again. Once the shell is done with it, the above ends up with the following value in the REGEX: `.*$.*`

I was able to successfully filter for strings containing `$` by escaping like:

```
export LA_SPARKLOGGINGEVENT_NAME_REGEX=".*\\\\\\\$read\\\\\\\$.*"
```

Each time this gets processed by the shell it collapses the double `\\` to a single, and the resulting string in the regex that gets loaded to the library still has `\$` values.

Since I was able to reproduce and workaround the problem by escaping the value of the environment variable, I'm going to go ahead and close this issue.  Feel free to reopen with additional details if you are still having problems.

**Closed by hallihan** 2021-09-10 19:35 UTC
