### ISSUE TITLE
Writing less streaming data

### ISSUE THREAD

**Issue by alaashafaee** [mspnp/spark-monitoring#86] opened 2020-06-03 12:18 UTC
We are monitoring structured streaming using the spark monitoring library. I am interested in progress events only. I set the log4j logging level to Info ("log4j.logger.org.apache.spark.sql.execution.streaming.StreamExecution=INFO"). This is still writing a lot of data. Is it possible to restrict this to progress events only? (i.e. QueryProgressEvent)

Thanks.

![image](https://user-images.githubusercontent.com/6775072/83764129-d8656a00-a679-11ea-8719-7ba39b97301a.png)

**Comment by hallihan** [comment] 2020-10-15 19:20
Closing this as a duplicate of #95 since this is a subset of the discussion there.

**Closed by hallihan** 2020-10-15 19:20 UTC
Labels: duplicate
