### ISSUE TITLE
Dropped Log Messages

### ISSUE THREAD

**Issue by bmoregeo** [mspnp/spark-monitoring#107] opened 2020-09-03 12:30 UTC
I am trying to track down why some log messages are being dropped when forwarded to Log Analytics. I do see the missing log messages in the log4j section in databricks.

I have some diagnostic logs at the beginning and end of a process to say what is being performed and when it was completed. Over a 24 hour period, 50% of the final 'completed' log messages are not being sent to log analytics.

There is not an obvious difference between those that do write to LA and those that do not. Each job run uses a fresh cluster as we are using ADF to spin up a cluster per each job. My current guess is there is some sort of buffer that is not getting dumped before the cluster spins down. 

Is this a known issue with a work around?

Thanks!

**Comment by hallihan** [comment] 2020-09-03 13:15
I think your guess may be correct that the process is getting shut down before the task is triggered to flush the buffer.  The default batch time is 5 seconds ([LogAnalyticsSendBuffer.java#L9](https://github.com/mspnp/spark-monitoring/blob/master/src/spark-listeners-loganalytics/src/main/java/com/microsoft/pnp/client/loganalytics/LogAnalyticsSendBuffer.java#L9)). 
I'm curious if the messages would all be delivered if you added a 5 second wait after the log message at the end of your process.  If that works, let me know and I'll file a workitem on our side to investigate a better solution.

**Comment by zizih** [comment] 2020-09-09 12:58
I meet the same problem, thanks both of you analysis and suggestion. I have reproduced the same issue in development. Add 5 seconds to wait after the log message is work. I have another suggestion, try to use:
`LogManager.shutdown()` 
it will flush all bufferred logs when shutting down the logManager

**Comment by stewartadam** [comment] 2020-09-28 19:13
Likely same root cause as for #71. Putting the whole code in a try/catch/finally block and sleeping 5 seconds before exit was the only solution I found, which is not ideal.

**Comment by hallihan** [comment] 2020-10-09 14:06
Closing as duplicate of #71

**Closed by hallihan** 2020-10-09 14:06 UTC
