### ISSUE TITLE
Grafana Dashboard error in Job and Stage Latency panels

### ISSUE THREAD

**Issue by al-lac** [mspnp/spark-monitoring#87] opened 2020-06-05 21:57 UTC
I get the following error on the Job and Stage Latency Panels when i deploy the grafana dashboard generated by the script:

`'extend' operator: Failed to resolve scalar expression named 'Properties_spark_metrics_namespace_s'`

Putting "Properties_spark_metrics_namespace_s" in both **"D"** queries in quotes seems to solve the issue.

**Comment by mathias-munk** [comment] 2020-08-07 13:46
I'm getting a Request failed status: 400 Bad Request for these tasks still. When I run the same queries in loganalytics, they work as intended. Is there anything I can do to resolve this? It's only the stage and job latency panels that don't work

**Comment by al-lac** [comment] 2020-08-18 09:27
Hi @mathias-munk, could you maybe take a look at the query inspector and post more details here?

**Comment by hallihan** [comment] 2020-11-13 14:12
It looks like the original issue here was fixed in #88.  @mathias-munk if you are stilling having problems, feel free to open a new issue with mode details.

**Closed by hallihan** 2020-11-13 14:12 UTC
