### ISSUE TITLE
Exact error messages as seen on "Stderr" on Databricks Spark UI are not being sent to Log Analytics Workspace, when spark-monitoring module has been configured as is described in README.md with default settings.

### ISSUE THREAD

**Issue by gt-murali-gsk** [mspnp/spark-monitoring#140] opened 2021-06-30 16:59 UTC
Dear Owners & Contributors,
We are seeing a few anomalies in the error descriptions logged to Log Analytics workspace vis-a-vis what we see on the Driver logs within Databricks workspace, when spark-monitoring module has already been configured on the databricks clusters as described in README.md. Could you please help confirm if correct columns are being queried to retrieve error messages, and why accurate error messages are not seen in log analytics.

Scenario-1: 
For the same error, error messages written to "Stderr" file within Databricks Workspace are not captured as they exactly are, into Log Analytics. Example:
Error logged into stderr file - "org.apache.spark.sql.AnalysisException: Table or view not found: vx_wm_cur`.`Dim_Storage_Unit33`; line 1 pos 0;"
Error seen in Log Analytics - "Failed to get database global_temp, returning NoSuchObjectException
HTTPRequest,Failed,cReqId:3a273245-fdfd-4ff7-b02d-89b0d393a4a6.0,lat:109,err:java.net.UnknownHostException,Reqlen:0,Resplen:0,token_ns:93709159,sReqId:null,path:/user/root/Dim_Storage_Unit33/_delta_log,qp:op=GETFILESTATUS&tooid=true&api-version=2017-08-01"
================================
Scenario-2:
Error logged into stderr file due to incorrect column name specified - org.apache.spark.sql.AnalysisException: cannot resolve '`LEIN.VBELN_temp`'
Error seen in Log Analytics - No corresponding error logged into Log Analytics. 
================================
In both scenarios above, SparkLoggingEvent_CL is being queried to retrieve the error messages for a particular run. Please refer to the below query being used for retrieving error messages:
SparkLoggingEvent_CL | where clusterId_s contains "girth" | where applicationId_s contains "app-20210624142949-0000" | order by TimeGenerated desc | where exception_exception_message_s != '' or Message != '' |  distinct exception_exception_message_s, Message

Thanks in advance!

**Comment by gt-murali** [comment] 2021-07-06 08:54
Hi Team,
Could anyone please help provide suggestions to overcome this issue!!
Thanks,
Murali

**Comment by hallihan** [comment] 2021-09-10 20:00
With the exception of [filtering](https://github.com/mspnp/spark-monitoring/blob/master/docs/filtering.md) the spark-monitoring library does not do any transformation on the data and is simply forwarding whatever is sent via the log4j appender.  Internally the messages are serialized as JSON.  I would not expect exact ordering since there is buffering and flushing on both sides.  Can you provide additional detail on where you are finding the STDERR logs (driver, executors, task logs, etc) and some steps to reproduce the behavior?

**Comment by hallihan** [comment] 2021-09-15 17:54
Closing out this issue pending additional information.  Please reopen with details if assistance is still needed.

**Closed by hallihan** 2021-09-15 17:54 UTC
